name: server_nano
version: 1.5.3
homepage: https://github.com/jonataslaw/dart-server-nano
description: A light, very fast, and friendly http and websocket server written in dart.

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  mime: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
